const references = {
  'spacing.1': 'var(--space-1)',
  'spacing.2': 'var(--space-2)',
  'spacing.3': 'var(--space-3)',
  'spacing.4': 'var(--space-4)',
  'spacing.5': 'var(--space-5)',
  'spacing.6': 'var(--space-6)',
  'spacing.8': 'var(--space-8)',
  'colors.accent': 'var(--fui-colors-accent)',
  'colors.accent-hover': 'var(--fui-colors-accent-hover)',
  'colors.accent-pressed': 'var(--fui-colors-accent-pressed)',
  'colors.accent-subtle': 'var(--fui-colors-accent-subtle)',
  'colors.border': 'var(--fui-colors-border)',
  'colors.border-strong': 'var(--fui-colors-border-strong)',
  'colors.canvas': 'var(--fui-colors-canvas)',
  'colors.card': 'var(--fui-colors-card)',
  'colors.control': 'var(--fui-colors-control)',
  'colors.control-border': 'var(--fui-colors-control-border)',
  'colors.control-bottom': 'var(--fui-colors-control-bottom)',
  'colors.control-hover': 'var(--fui-colors-control-hover)',
  'colors.control-pressed': 'var(--fui-colors-control-pressed)',
  'colors.danger': 'var(--fui-colors-danger)',
  'colors.danger-bg': 'var(--fui-colors-danger-bg)',
  'colors.disabled': 'var(--fui-colors-disabled)',
  'colors.focus': 'var(--fui-colors-focus)',
  'colors.info-bg': 'var(--fui-colors-info-bg)',
  'colors.on-accent': 'var(--fui-colors-on-accent)',
  'colors.on-primary': 'var(--fui-colors-on-primary)',
  'colors.primary': 'var(--fui-colors-primary)',
  'colors.primary-hover': 'var(--fui-colors-primary-hover)',
  'colors.primary-pressed': 'var(--fui-colors-primary-pressed)',
  'colors.success': 'var(--fui-colors-success)',
  'colors.success-bg': 'var(--fui-colors-success-bg)',
  'colors.surface': 'var(--fui-colors-surface)',
  'colors.surface-hover': 'var(--fui-colors-surface-hover)',
  'colors.surface-muted': 'var(--fui-colors-surface-muted)',
  'colors.surface-pressed': 'var(--fui-colors-surface-pressed)',
  'colors.surface-raised': 'var(--fui-colors-surface-raised)',
  'colors.text': 'var(--fui-colors-text)',
  'colors.text-muted': 'var(--fui-colors-text-muted)',
  'colors.text-subtle': 'var(--fui-colors-text-subtle)',
  'colors.warning': 'var(--fui-colors-warning)',
  'colors.warning-bg': 'var(--fui-colors-warning-bg)',
  'fonts.body': 'var(--fui-fonts-body)',
  'fonts.display': 'var(--fui-fonts-display)',
  'fonts.mono': 'var(--fui-fonts-mono)',
  'radii.sm': 'var(--fui-radii-sm)',
  'radii.md': 'var(--fui-radii-md)',
  'radii.lg': 'var(--fui-radii-lg)',
} as const;
export const token = {
  var(path: keyof typeof references): string {
    const value = references[path];
    if (!value) throw new Error(`Unknown token: ${path}`);
    return value;
  },
};
