import { definePreset } from './define-config.ts';
/** Existing public variables stay the source of Fluent theme values. */
export const fluentPreset = definePreset({
  theme: {
    tokens: {
      spacing: {
        1: { value: '4px' },
        2: { value: '8px' },
        3: { value: '12px' },
        4: { value: '16px' },
        5: { value: '20px' },
        6: { value: '24px' },
        8: { value: '32px' },
      },
      fonts: {
        body: { value: 'var(--font-body)' },
        display: { value: 'var(--font-display)' },
        mono: { value: 'var(--font-mono)' },
      },
      radii: {
        sm: { value: 'var(--radius-sm)' },
        md: { value: 'var(--radius-md)' },
        lg: { value: 'var(--radius-lg)' },
      },
    },
    semanticTokens: {
      colors: {
        accent: { value: 'var(--color-accent)' },
        'accent-hover': { value: 'var(--color-accent-hover)' },
        'accent-pressed': { value: 'var(--color-accent-pressed)' },
        'accent-subtle': { value: 'var(--color-accent-subtle)' },
        border: { value: 'var(--color-border)' },
        'border-strong': { value: 'var(--color-border-strong)' },
        canvas: { value: 'var(--color-canvas)' },
        card: { value: 'var(--color-card)' },
        control: { value: 'var(--color-control)' },
        'control-border': { value: 'var(--color-control-border)' },
        'control-bottom': { value: 'var(--color-control-bottom)' },
        'control-hover': { value: 'var(--color-control-hover)' },
        'control-pressed': { value: 'var(--color-control-pressed)' },
        danger: { value: 'var(--color-danger)' },
        'danger-bg': { value: 'var(--color-danger-bg)' },
        disabled: { value: 'var(--color-disabled)' },
        focus: { value: 'var(--color-focus)' },
        'info-bg': { value: 'var(--color-info-bg)' },
        'on-accent': { value: 'var(--color-on-accent)' },
        'on-primary': { value: 'var(--color-on-primary)' },
        primary: { value: 'var(--color-primary)' },
        'primary-hover': { value: 'var(--color-primary-hover)' },
        'primary-pressed': { value: 'var(--color-primary-pressed)' },
        success: { value: 'var(--color-success)' },
        'success-bg': { value: 'var(--color-success-bg)' },
        surface: { value: 'var(--color-surface)' },
        'surface-hover': { value: 'var(--color-surface-hover)' },
        'surface-muted': { value: 'var(--color-surface-muted)' },
        'surface-pressed': { value: 'var(--color-surface-pressed)' },
        'surface-raised': { value: 'var(--color-surface-raised)' },
        text: { value: 'var(--color-text)' },
        'text-muted': { value: 'var(--color-text-muted)' },
        'text-subtle': { value: 'var(--color-text-subtle)' },
        warning: { value: 'var(--color-warning)' },
        'warning-bg': { value: 'var(--color-warning-bg)' },
      },
    },
  },
});
